# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_file_segment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AddField(
            model_name='file',
            name='docfile',
            field=models.FileField(default='null', upload_to='user_files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
