# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20180515_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordker_id', models.CharField(max_length=100, null=True)),
                ('label_datetime', models.DateTimeField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('segment_duration', models.DecimalField(decimal_places=5, max_digits=7)),
                ('step_size', models.DecimalField(decimal_places=5, max_digits=7)),
                ('max_total_responses', models.IntegerField()),
                ('min_responses_per_segment', models.IntegerField()),
                ('max_responses_per_segment', models.IntegerField()),
                ('threshold', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Study')),
            ],
        ),
        migrations.CreateModel(
            name='StudyWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Study')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='segment',
            name='label',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='label_datetime',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='user',
        ),
        migrations.AddField(
            model_name='response',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Segment'),
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Study'),
        ),
        migrations.AddField(
            model_name='segment',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Study'),
            preserve_default=False,
        ),
    ]
