# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 19:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180522_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='docfile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='study',
            name='creation_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
