# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180523_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='wordker_id',
            new_name='worker_id',
        ),
        migrations.AddField(
            model_name='segment',
            name='status',
            field=models.CharField(default='low_priority', max_length=13),
        ),
    ]
