# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180523_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='max_responses_per_worker',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
